dist: xenial
language: python
cache: pip
notifications:
  email: false
sudo: true

pip:
 - pip install git+git://github.com/Rapptz/discord.py.git#egg=discord.py[voice]
script:
 - python3 -m compileall .
