name: Style check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  style-check:
    runs-on: ubuntu-latest
    name: Style check

    steps:
      - uses: actions/checkout@v2

      - name: Black Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "--check --diff ."
